databases:
  - name: abeabea_DB
    databaseName: abeabea_db
    user: abeabea
    region: singapore

services:
  - type: web
    name: abeabea
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: abeabea_DB
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

